version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=cesupadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
